name: Update-Test-Publish-Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        working-directory: ./scripts/slmatchups
        run: |
          python -m pip install --upgrade pip pytest
          pip install -r requirements.txt --prefer-binary
      - name: test py script
        working-directory: ./scripts/slmatchups
        run: |
          pytest test_main.py
      - name: execute py script
        working-directory: ./scripts/slmatchups
        run: |
          python main.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: berryscottr
          author_email: berryscottr@gmail.com
          message: 'Automated commit of skill updates'
          add: '.'
      - name: Push changes
        run: |
          git push
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
  publish:
    runs-on: ubuntu-latest
    needs: [update, test]
    steps:
      - uses: actions/checkout@v4
      - name: Login to Github Package Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository }} --password-stdin
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag magic-8ball:latest --build-arg BOT_TOKEN=${{ secrets.BOT_TOKEN }}
      - name: Tag the Docker image
        run: docker tag magic-8ball:latest docker.pkg.github.com/berryscottr/magic-8ball/magic-8ball:latest
      - name: Push the Docker image
        run: docker push docker.pkg.github.com/berryscottr/magic-8ball/magic-8ball:latest
      # - name: Run the Docker image
      #   run: docker run docker.pkg.github.com/berryscottr/magic-8ball/magic-8ball:latest
      # - uses: gautamkrishnar/keepalive-workflow@v1
  