name: Undeploy 
on: 
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 3 * * 3"

jobs:
  undeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        run: |
          RAILWAY_TOKEN=$RAILWAY_TOKEN railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
