name: Update
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        working-directory: ./scripts/slmatchups
        run: |
          python -m pip install --upgrade pip pytest
          pip install -r requirements.txt --prefer-binary
      - name: test py script
        working-directory: ./scripts/slmatchups
        run: |
          pytest test_main.py
      - name: execute py script
        working-directory: ./scripts/slmatchups
        run: |
          python main.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: berryscottr
          author_email: berryscottr@gmail.com
          message: 'Automated commit of skill updates'
          add: '.'
      - name: Push changes
        run: |
          git push