name: updateCal

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install dependencies
        working-directory: ./data
        run: |
          python -m pip install --upgrade pip pandas
      - name: execute py script
        working-directory: ./data
        run: |
          python -c 'import pandas as pd; f = pd.read_excel("Fall2022Schedule.xlsx"); f.to_csv("Fall2022Schedule.csv", index=None, header=True)'
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: berryscottr
          author_email: berryscottr@gmail.com
          message: 'Automated commit of schedule updates'
          add: '.'
      - name: Push changes
        run: |
          git push